name: Node.js CI/CD

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build and Deploy
        run: |
          # Add your deployment steps here, e.g., deploying to a hosting service
          # Example: npm run build && npm run deploy
